# Generated by Django 3.0.7 on 2020-07-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('ID_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100, verbose_name='Nome:')),
                ('data_validade', models.DateField(verbose_name='Data de validade:')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço:')),
                ('quantidade_produto', models.IntegerField(verbose_name='Quantidade de produtos:')),
            ],
        ),
    ]
