# Generated by Django 3.0.7 on 2020-07-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='Nome:')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF:')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('ID_compra', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço:')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço:'),
        ),
    ]
