# Generated by Django 3.0.7 on 2020-07-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_auto_20200719_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='compra_produto',
            field=models.ManyToManyField(to='mercado.Produto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor total:'),
        ),
    ]
