# Generated by Django 3.0.7 on 2020-07-20 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_auto_20200719_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='FK_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mercado.Cliente'),
        ),
    ]
