# Generated by Django 3.0.7 on 2020-07-20 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0005_delete_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('ID_compra', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor total:')),
                ('FK_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.Cliente')),
                ('compra_produto', models.ManyToManyField(to='mercado.Produto')),
            ],
        ),
    ]
