# Generated by Django 3.0.7 on 2020-07-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0006_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('ID_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=45, verbose_name='Nome Categoria:')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('ID_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fornecedor', models.CharField(max_length=100, verbose_name='Nome:')),
                ('email_fornecedor', models.CharField(max_length=100, verbose_name='Email:')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ:')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone:')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('ID_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(max_length=45, verbose_name='Nome:')),
                ('rg', models.CharField(max_length=15, verbose_name='RG:')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF:')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('ID_setor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_setor', models.CharField(max_length=45, verbose_name='Setor:')),
            ],
        ),
    ]
