# Generated by Django 3.0.7 on 2020-07-20 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0009_categoria_cliente_compra_fornecedor_funcionario_produto_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='FK_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.Cliente', verbose_name='Cliente:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='FK_setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.Setor', verbose_name='Setor:'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='FK_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.Categoria', verbose_name='Categoria:'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='FK_fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.Fornecedor', verbose_name='Fornecedor:'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='FK_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.Categoria', verbose_name='Categoria:'),
        ),
    ]
