# Generated by Django 3.0.7 on 2020-07-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0010_auto_20200720_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name_plural': 'Setores'},
        ),
    ]
