# Generated by Django 3.0.7 on 2020-07-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0011_auto_20200720_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ:'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(max_length=13, verbose_name='Telefone:'),
        ),
    ]
